console.log('Ailton was born in 1996')
console.log('In 2024 Ailton met Andressa ')
console.log('Ailton married Andressa in 2030')
console.log('Andressa had a child with Ailton in 2030')
console.log("Ailton's son's name is Edward ")
